// Sous-interface pour les notes
export interface Note {
    _id?: string;
    matiere: string;
    note: number;
    coefficient: number;
    date: Date | string;
    semestre?: string;
    type: 'examen' | 'controle' | 'tp' | 'projet';
}

// Sous-interface pour les documents
export interface Document {
    _id?: string;
    nom: string;
    type: 'diplome' | 'certificat' | 'cv' | 'carte_identite' | 'autre';
    url: string;
    dateUpload: Date | string;
    taille?: number;
}

export class Etudiants {
    // Identifiants
    id?: number; // Optional since it's auto-generated by the backend
    numeroEtudiant?: string;
    
    // Informations de base (REQUIRED)
    nom: string;
    prenom: string;
    mail: string;
    photo: string;
    
    // Informations personnelles
    dateNaissance?: Date | string;
    lieuNaissance?: string;
    genre?: 'M' | 'F' | 'Autre';
    nationalite?: string;
    
    // Contact
    telephone?: string;
    telephoneParent?: string;
    adresse?: string;
    ville?: string;
    codePostal?: string;
    pays?: string;
    
    // Informations académiques
    niveau?: string;
    filiere?: string;
    matieres: string[];
    anneeInscription?: number;
    statut?: 'actif' | 'inactif' | 'diplome' | 'suspendu' | 'abandonne';
    
    // Notes et évaluations
    notes?: Note[];
    
    // Documents
    documents?: Document[];
    
    // Informations complémentaires
    boursier?: boolean;
    redoublant?: boolean;
    remarques?: string;
    
    // Timestamps
    createdAt?: Date | string;
    updatedAt?: Date | string;
    
    // Virtuels (calculés côté backend)
    moyenneGenerale?: number;
    age?: number;
    nomComplet?: string;
    
    // UI state (not saved to backend)
    selected?: boolean;
}